name: PR Title Automated linking
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  enforce-and-automate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Validate PR title and link to Issue
        uses: distributeaid/centralised-github-actions/.github/actions/pr-title-check-linking@NOISSUE-pr-title-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
            